### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by MPParsley** [add-ons/plugin.video.viervijfzes#61]
The plugin doesn't appear in the video plugins section on Leia.

Is there a specific Kodi version requirement or hasn't [this plugin been submitted yet](https://kodi.wiki/view/Submitting_Add-ons)?

**Comment by michaelarnauts** [comment]
It hasn't been submitted. The reason is that we don't display ads, and I believe this would be against the terms of use of SBS Belgium.

**Comment by MPParsley** [comment]
Makes sense, thanks for the reply (and all these awesome plugins)!

I [installed it from zip as mentioned in the documentation](https://github.com/add-ons/plugin.video.viervijfzes/wiki/Installatie).

**Comment by michaelarnauts** [comment]
Also, there is a nasty issue that causes some streams to be unplayable with skips due to the format of the streams. On a RPI, this seems to work fine, but not on other platforms.

I might change my mind though, but I think SBS Belgium will come with an updated offering next year that includes a new channel Zeven. I hope they use a new backend for this that delivers better streams, and I will probably create a new Addon for that then, since this won't work anymore then.
